pipeline {

    agent {
        docker {
            image 'python'
            args '-v $HOME/.m2:/root/.m2'
        }
    }

    stages {
        stage('build') {
            when {
                changeset '**/vote/**'
            }
            steps {
                echo 'Compiling vote app'
                dir('vote') {
                    sh 'pip install -i requirements.txt'
                }
            }
        }
        stage('test') {
            when {
                changeset '**/vote/**'
            }
            steps {
                echo 'Running unit tests on vote app'
                dir('vote') {
                    sh 'nosetests -v'
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline for vote is completed..'
        }
    }
}
